# Generated by Django 4.1.7 on 2023-04-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_rename_veiculos_veiculo_alter_acessorio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'cores'},
        ),
    ]
